-- DriveCost v3.0.0 — Production schema for Supabase
-- Run this entire file in Supabase SQL Editor before deploying to Render.
-- It is idempotent and can be run again after updates.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) <= 80),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_sync_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  revision bigint not null default 0 check (revision >= 0),
  client_updated_at timestamptz,
  device_id text check (char_length(device_id) <= 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'auditor'
    check (role in ('owner', 'auditor', 'support')),
  active boolean not null default true,
  note text check (char_length(note) <= 500),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  admin_email_masked text check (char_length(admin_email_masked) <= 160),
  action text not null check (char_length(action) <= 100),
  target_type text not null default 'system'
    check (char_length(target_type) <= 80),
  target_id text check (char_length(target_id) <= 160),
  metadata jsonb not null default '{}'::jsonb,
  ip_hash text check (char_length(ip_hash) <= 64),
  created_at timestamptz not null default now()
);

create index if not exists profiles_updated_at_idx
  on public.profiles(updated_at desc);

create index if not exists user_sync_state_updated_at_idx
  on public.user_sync_state(updated_at desc);

create index if not exists user_sync_state_revision_idx
  on public.user_sync_state(revision);

create index if not exists app_admins_active_idx
  on public.app_admins(active)
  where active = true;

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log(created_at desc);

create index if not exists admin_audit_log_admin_user_idx
  on public.admin_audit_log(admin_user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.user_sync_state enable row level security;
alter table public.app_admins enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "sync_select_own" on public.user_sync_state;
create policy "sync_select_own"
on public.user_sync_state for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "sync_insert_own" on public.user_sync_state;
create policy "sync_insert_own"
on public.user_sync_state for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "sync_update_own" on public.user_sync_state;
create policy "sync_update_own"
on public.user_sync_state for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- app_admins and admin_audit_log intentionally have no authenticated policies.
-- Only the Render server's Supabase secret key may access them.

revoke all on public.app_admins from anon, authenticated;
revoke all on public.admin_audit_log from anon, authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.user_sync_state to authenticated;

grant select, insert, update, delete on public.app_admins to service_role;
grant select, insert on public.admin_audit_log to service_role;
grant usage, select on sequence public.admin_audit_log_id_seq to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_sync_state_set_updated_at
  on public.user_sync_state;
create trigger user_sync_state_set_updated_at
before update on public.user_sync_state
for each row execute function public.set_updated_at();

drop trigger if exists app_admins_set_updated_at on public.app_admins;
create trigger app_admins_set_updated_at
before update on public.app_admins
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    nullif(
      left(
        coalesce(new.raw_user_meta_data ->> 'display_name', ''),
        80
      ),
      ''
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Backfill profiles for users created before the trigger existed.
insert into public.profiles (id, display_name)
select
  users.id,
  nullif(
    left(
      coalesce(users.raw_user_meta_data ->> 'display_name', ''),
      80
    ),
    ''
  )
from auth.users as users
left join public.profiles as profiles
  on profiles.id = users.id
where profiles.id is null
on conflict (id) do nothing;

create or replace function public.save_user_sync_state(
  p_expected_revision bigint,
  p_payload jsonb,
  p_client_updated_at timestamptz,
  p_device_id text
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_row public.user_sync_state%rowtype;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if jsonb_typeof(coalesce(p_payload, '{}'::jsonb)) <> 'object' then
    raise exception 'Payload must be a JSON object';
  end if;

  if pg_column_size(coalesce(p_payload, '{}'::jsonb)) > 2097152 then
    raise exception 'Payload exceeds 2 MB';
  end if;

  insert into public.user_sync_state (
    user_id,
    payload,
    revision,
    client_updated_at,
    device_id
  )
  values (
    v_user_id,
    coalesce(p_payload, '{}'::jsonb),
    1,
    p_client_updated_at,
    left(p_device_id, 120)
  )
  on conflict (user_id) do nothing
  returning * into v_row;

  if found then
    return jsonb_build_object(
      'saved', true,
      'revision', v_row.revision,
      'payload', v_row.payload,
      'updated_at', v_row.updated_at
    );
  end if;

  update public.user_sync_state
  set
    payload = coalesce(p_payload, '{}'::jsonb),
    revision = revision + 1,
    client_updated_at = p_client_updated_at,
    device_id = left(p_device_id, 120)
  where
    user_id = v_user_id
    and revision = greatest(coalesce(p_expected_revision, 0), 0)
  returning * into v_row;

  if found then
    return jsonb_build_object(
      'saved', true,
      'revision', v_row.revision,
      'payload', v_row.payload,
      'updated_at', v_row.updated_at
    );
  end if;

  select *
  into v_row
  from public.user_sync_state
  where user_id = v_user_id;

  return jsonb_build_object(
    'saved', false,
    'revision', coalesce(v_row.revision, 0),
    'payload', coalesce(v_row.payload, '{}'::jsonb),
    'updated_at', v_row.updated_at
  );
end;
$$;

revoke all on function public.save_user_sync_state(
  bigint,
  jsonb,
  timestamptz,
  text
) from public;

grant execute on function public.save_user_sync_state(
  bigint,
  jsonb,
  timestamptz,
  text
) to authenticated;

create or replace function public.admin_system_integrity()
returns jsonb
language sql
security definer
set search_path = public, auth
as $$
  select jsonb_build_object(
    'profiles_count',
      (select count(*) from public.profiles),

    'sync_count',
      (select count(*) from public.user_sync_state),

    'admin_count',
      (select count(*) from public.app_admins where active = true),

    'audit_count',
      (select count(*) from public.admin_audit_log),

    'profiles_without_sync',
      (
        select count(*)
        from public.profiles as profiles
        left join public.user_sync_state as sync
          on sync.user_id = profiles.id
        where sync.user_id is null
      ),

    'sync_without_profile',
      (
        select count(*)
        from public.user_sync_state as sync
        left join public.profiles as profiles
          on profiles.id = sync.user_id
        where profiles.id is null
      ),

    'authless_profiles',
      (
        select count(*)
        from public.profiles as profiles
        left join auth.users as users
          on users.id = profiles.id
        where users.id is null
      ),

    'stale_sync_30d',
      (
        select count(*)
        from public.user_sync_state
        where updated_at < now() - interval '30 days'
      ),

    'revision_zero',
      (
        select count(*)
        from public.user_sync_state
        where revision = 0
      ),

    'invalid_payloads',
      (
        select count(*)
        from public.user_sync_state
        where jsonb_typeof(payload) <> 'object'
      ),

    'large_payloads',
      (
        select count(*)
        from public.user_sync_state
        where pg_column_size(payload) > 524288
      ),

    'max_payload_bytes',
      coalesce(
        (
          select max(pg_column_size(payload))
          from public.user_sync_state
        ),
        0
      ),

    'avg_payload_bytes',
      coalesce(
        (
          select round(avg(pg_column_size(payload)))
          from public.user_sync_state
        ),
        0
      ),

    'latest_sync_at',
      (
        select max(updated_at)
        from public.user_sync_state
      )
  );
$$;

revoke all on function public.admin_system_integrity() from public;
revoke all on function public.admin_system_integrity() from anon;
revoke all on function public.admin_system_integrity() from authenticated;
grant execute on function public.admin_system_integrity() to service_role;

-- The production app no longer uses Realtime as a write trigger.
-- Remove user_sync_state from the publication to prevent unnecessary events.
do $$
begin
  if exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'user_sync_state'
  ) then
    alter publication supabase_realtime
      drop table public.user_sync_state;
  end if;
end
$$;

commit;

-- Bootstrap an administrator after running this file:
--
-- 1. Find the user's UUID in Authentication > Users.
-- 2. Replace the UUID below and run only this statement:
--
-- insert into public.app_admins (user_id, role, note)
-- values (
--   '00000000-0000-0000-0000-000000000000',
--   'owner',
--   'Primary DriveCost administrator'
-- )
-- on conflict (user_id)
-- do update set
--   active = true,
--   role = excluded.role,
--   note = excluded.note;
--
-- You may also bootstrap access through the Render ADMIN_EMAILS environment
-- variable. Database membership is recommended for long-term administration.
